template(name="Server1Format" type="string"
         string="%timegenerated% %syslogseverity-text% %HOSTNAME% %syslogtag%%msg%\n")

if ($hostname == 'server1') and ($syslogseverity <= 4) then {
    action(
        type="omfile"
        file="/var/log/server1_important.log"
        template="Server1Format"
    )
    stop
}
